### ISSUE TITLE
izzard

### ISSUE THREAD

**Issue by jimregan** [kscanne/wordnet-gaeilge#12]
```
#. IG; N=letter z
#. ga=iseard
msgid "izzard  n"
msgstr "izzard%1:10:00::"
```

[izzard](https://en.wiktionary.org/wiki/izzard) is a Scottish name for the letter Z; [izard](https://en.wiktionary.org/wiki/izard) (Pyrenean chamois) should be the translation of 'iseard' (missing from Wordnet)

**Comment by kscanne** [comment]
thanks, well-spotted.  I just pushed the latest version of the database with a fix for this included.
